# Generated by Django 4.0.5 on 2023-02-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_remove_song_file_song_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('cover', models.URLField(max_length=2000)),
                ('status', models.IntegerField(choices=[(1, 'Backlog'), (2, 'Playing'), (3, 'Done')])),
            ],
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
