# Generated by Django 4.0.5 on 2023-03-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_delete_playlist_delete_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
