# Generated by Django 4.0.5 on 2023-03-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timer',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
