# Generated by Django 4.0.5 on 2023-02-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_song_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.IntegerField(choices=[(1, 'Backlog'), (2, 'Playing'), (3, 'Done')], default=1),
            preserve_default=False,
        ),
    ]
